### ISSUE TITLE
Add low threshold actions

### ISSUE THREAD

**Issue by precision** [google/OctoPrint-TemperatureFailsafe#1]
Add an additional failsafe in the event that the thermistor itself fails and starts reading 0 degrees

**Comment by Brandoskey** [comment]
Glad you've taken this into consideration. I'm not totally sure if my maker select plus will shut itself down if the thermistor fails, but this will bring an extra layer of peace of mind.

**Comment by djrej** [comment]
Yes I was looking for this.

Is it possible to set the low threshold manually instead of waiting for the temp reading to 0 degrees?

The Threshold will only trigger when the printer starts and stops when the printing is done.

**Comment by precision** [comment]
I think I have what you two are asking for working in my personal [fork](https://github.com/precision/OctoPrint-TemperatureFailsafe).  If you get a chance, check it out, you can install it by using the URL https://github.com/precision/OctoPrint-TemperatureFailsafe/archive/master.zip in the plugin manager.

**Comment by djrej** [comment]
Sorry I think you misunderstood what I meant.

You are adding a fail safe in the event of a thermistor failure, I was suggesting instead of waiting for the reading to become 0 degrees, is it possible to set the threshold manually, also it will only be activated when the print starts and deactivate when the print is done.

From my understanding the failed thermistor will read the environment temp if it gets disconnected to the heat block in which it will continue to heat up the hot end. 

BTW I highly recommend your plugin and what an outstanding job you did!

**Comment by Brandoskey** [comment]
In my experience with a failed thermistor wire I got a 0 reading when the thermistor was unable to report temp due to a bad wire connection.

BTW, installing the new plugin now.

djrej, looks like the new plugin allows you to set the low threshold manually. I don't see an option to enable it only during the print though.

**Comment by precision** [comment]
I hard set the low threshold to only fire during printing, since it doesn't make a whole lot of sense to turn off the printer (or whatever) because of a failed thermistor when the printer is just sitting there.   I suppose I could still fire the cancel print/disable heaters though.

**Comment by djrej** [comment]
Perfect!

Just thinking of how I'll be able to test it lol

Thanks!

**Comment by precision** [comment]
@djrej That was part of my problem as well, the code looks like it should work, but I'll need to crack open a printer and disconnect the thermistor mid print to actually verify it.

**Comment by djrej** [comment]
how about set the temp down below the threshold while printing or disconnect the thermistor on the board.

**Comment by precision** [comment]
Yeah, that works, I did that with the virtual printer and it fires the failsafe.  I was just hoping to have a slightly more real work test before I push this to the main tree.

**Comment by djrej** [comment]
I will do some test later when I get home.

**Comment by djrej** [comment]
My test result when I set the hot bed to 0 Degrees is as follows.
HotBed Temp is set to 65 Degrees
HotBed Low Threshold: 40 Degrees

* It took more than 10 Min. to reach the low threshold.
* It canceled the print
* 3D printer was turned off

Do I have to remove the shutdown script so it will only cancel the print?

**Comment by precision** [comment]
That sounds like the expected behavior, the current code will execute the failsafe command for low threshold violations.  However, you can have your failsafe command be smart about what it does.  The plugin inserts some variables into the shell environment you can use to check if you hit the low threshold.  

TEMPERATURE_FAILSAFE_FAULT_TOOL the tool name (tool0, tool1, bed) in octoprint speak
TEMPERATURE_FAILSAFE_FAULT_THRESHOLD the threshold temperature that was violated
TEMPERATURE_FAILSAFE_%s_ACTUAL (replace %s with the tool0, tool1, bed naming) temperature
TEMPERATURE_FAILSAFE_%s_TARGET (same, except it was the target when the script fired)

You could wrap your shutdown command in a shell script with a simple check of those variables to determine if it should or shouldn't shut the printer off.

**Comment by precision** [comment]
Here is an example of the environment variables available.
```
TEMPERATURE_FAILSAFE_BED_ACTUAL=1.0
TEMPERATURE_FAILSAFE_BED_TARGET=1.0
TEMPERATURE_FAILSAFE_TOOL0_ACTUAL=103.83
TEMPERATURE_FAILSAFE_TOOL0_TARGET=105.0
TEMPERATURE_FAILSAFE_FAULT_THRESHOLD=100
TEMPERATURE_FAILSAFE_FAULT_TOOL=tool0

```
