### ISSUE TITLE
The plugin is not displayed after installation

### ISSUE THREAD

**Issue by willhoh** [google/OctoPrint-TemperatureFailsafe#13]
The plugin is not displayed after installation.

I installed "TemperatureFailsafe" via the URL on the 1.4.0rc3, but the plugin is not displayed in the settings. According to the installation window it runs without problems. Also in the log I don't see any messages, also none that "TemperatureFailsafe" is running.
Please tell me what information or logs are necessary to help.

edit: here the log [installation](https://pastebin.com/eRsC75kz)

**Comment by precision** [comment]
The install log looks fine. Lets start with ~/.octoprint/logs/octoprint.log and see if there are any hints there. 

If you would like some extra debugging information you can put the following in ~/.octoprint/logging.yaml But since it sounds like the plugin isn't even being loaded I'm not sure how helpful that will be.
```
loggers:
  octoprint.plugins.TemperatureFailsafe:
    level: DEBUG
```

**Comment by willhoh** [comment]
Here is the octoprint.log.
Sorry for that delay. Had to figure out why PI to Printer connection results in stuttering by printing circles.

[octoprint.log](https://gist.github.com/willhoh/5a83b3a91ea1d814d960b0b2500b42b7)

edit: 
In Settings > Logging, I can't set logging level for TemperatureFailsafe. In comparison, I have also installed PSU-Control and can set the logging level for this.

**Comment by precision** [comment]
It looks like you're running OctoPrint 1.4.0rc3 under Python 3.7.  I'll have to see if I can get some time to test the plugin there.  In theory the plugin shouldn't even have showed up in the plugin manager to install under 1.4.

**Comment by precision** [comment]
If you'd like to test yourself you can add the following to /home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint_TemperatureFailsafe/__init__.py on line 200.

```
__plugin_pythoncompat__ = ">=2.7,<4"
```

**Comment by willhoh** [comment]
It worked like a charm. 

I have now installed this via my fork, but would be very grateful if you would add it to the master and publish it.
