### ISSUE TITLE
polling after print started

### ISSUE THREAD

**Issue by mustatommi** [google/OctoPrint-TemperatureFailsafe#4]
Hi, I'm having this issue:
when i start printing, the bed and the extruder are heated up first and then, when both temp are reached, the print effectively start.
The plugin start polling since the very beginning, while extruder and bed are still in the heat up process, and thus it shut down the print job even if the printing is not started.

Would be possible to add an option check the printing is started before starting polling for thermal runaway?

Thanks!

**Comment by precision** [comment]
That would be possible. However the plugin should only trigger if you go over the threshold, which should be well above your normal printing temperatures.   Is the plugin triggering before that?

**Comment by mustatommi** [comment]
Ok… but if that’s the way is meant to be, why there’s a minimum temp limit?
I think it would be nice to be able to stop a printing job if for whatever reason (failing mosfet, connection or wrong code) the temp fall lower than expected, saving you from clogged noozle or worst, burnt extruder motor… but then you’d needto start polling after Printing is started

just my two cents 😊


Da: Uriah Welcome
Inviato: giovedì 29 giugno 2017 22:50
A: google/OctoPrint-TemperatureFailsafe
Cc: mustatommi; Author
Oggetto: Re: [google/OctoPrint-TemperatureFailsafe] polling after printstarted (#4)

That would be possible. However the plugin should only trigger if you go over the threshold, which should be well above your normal printing temperatures. Is the plugin triggering before that?

**Comment by precision** [comment]
Minimum temp is intended to handle the case where your thermistor fails or the wires breaks.  It should be set to something lower than ambient temperature like 5C.

**Comment by mustatommi** [comment]
Oki, thanks!

T

Da: Uriah Welcome
Inviato: venerdì 30 giugno 2017 08:57
A: google/OctoPrint-TemperatureFailsafe
Cc: mustatommi; Author
Oggetto: Re: [google/OctoPrint-TemperatureFailsafe] polling after printstarted (#4)

Minimum temp is intended to handle the case where your thermistor fails or the wires breaks. It should be set to something lower than ambient temperature like 5C.
