### ISSUE TITLE
Failsafes stops print during heatup

### ISSUE THREAD

**Issue by fakio87** [google/OctoPrint-TemperatureFailsafe#6]
Hi,

I have the problem, that failsafe will only work, when I preheat my printer manually.

As soon as I start a print without preheating the plugin will stop the print as the temo will be below the "low temp" parameter.

I could keep that parameter empty, however sometimes my printer is stopping heating when the print starts but keeps going which can lead to alot of stress for the extruder/nozzle if I am not present.

Is there any work around, that the failsafe will wait for the print to start until it is activated?

**Comment by precision** [comment]
The low temperature threshold is really meant to detect more of a thermistor failure / disconnected / wire break or short.  It should be set to just below normal room temperature.  I should probably be a little more clear in the README what that option is for.  Can you try setting it to something just below room temp and see if you still have a problem with it spuriously firing?

**Comment by fakio87** [comment]
Hi, thank you for the fast reply!

Sure, I understand the meaning and how to avoid that issue. Thank you for
explaining.

Practically this will not help me with the reason I put the threshold that
high. But it is okay,

I will just preheat manually.

Uriah Welcome <notifications@github.com> schrieb am Sa. 11. Nov. 2017 um
17:03:

**Comment by precision** [comment]
Can you explain to me your use case?  I don't mind adding a little more logic to the lowside failsafe, I just want to understand what you're trying to accomplish by having it set higher.

**Comment by fakio87** [comment]
Hi,

from time to time the following scenario is happening:

I start a print.
Heatbed is heating up
Hotend is heating up
Printer is homing all axis
heaters are switched off (Don't know why, happens or doesn't happen with
the same gcode)
Printer starts printing
E-Stepper feeds filament into the nozzle that is cooling down

In case that happens I want the printer to notice and stop the print job.

Uriah Welcome <notifications@github.com> schrieb am Sa. 11. Nov. 2017 um
20:57:

**Comment by jeffmaeder** [comment]
At first when adding this plugin I thought it would only protect the case where the temp runs out of control high. To my surprise it actually had protection for low temp set points as well. The failure mode I was experiencing was similar to fakio87, after I started a print at some point the heated bed would stop heating. As a result the print would shrink and detach from the bed and well.....everyone has seen it! It turns out some of the solder joints on the mosfet I was using for the heated bed had become compromised . If this Plugin would start examining the temperatures after the "M117 Printing..." line in the starting gcode it would protect against the temp drifting low during a print. This way you wouldn't have to manually preheat the printer.

**Comment by precision** [comment]
It sounds like you want the equivalent of [Marlins thermal protection](http://marlinfw.org/docs/configuration/configuration.html#safety) then?  I don't think that'd be all that difficult to add to the plugin.  I'll see if I can add something later this week.

**Comment by jeffmaeder** [comment]
Yes that sounds exactly like what i'm describing.  Thank you very much for looking into it.

**Comment by fakio87** [comment]
If you could add the option to start the Failsafe from M117 despite from heatup that'b great. 

Somehow since my last update I cannot install failsafe anyway. I guess all plugins need to be updated to show up in the latest version of octoprint?

**Comment by precision** [comment]
@fakio87 I'd be happy to review a patch, however having the plugin only start once a print has been activated is counter to what I use/want this plugin.  I use/intended this plugin for a backup failsafe in case my AC SSRs were to fail closed, which theoretically could happen at any time.
