### ISSUE TITLE
cancels before reaching temp...

### ISSUE THREAD

**Issue by damanbaird** [google/OctoPrint-TemperatureFailsafe#9]
what can be done to add a " wait for temp " code, with plugin enabled and i start to print plugin automatically cancels print before printer reaches temp.

**Comment by precision** [comment]
I'm not sure what you're asking.. Is your printer taking longer than the timeout to reach the target temperature?

**Comment by damanbaird** [comment]
Im thinking it was gonna work more like Marlins i guess, i read some of the other issues people posted about it, i also have the low temp set higher then you had planned.

**Comment by damanbaird** [comment]
oh, i may have misunderstood "command timeout" is this at the beginning ? A timeout before it starts monitoring?

**Comment by precision** [comment]
That is the timeout that it waits for the external shutdown command to execute before killing the thread.

**Comment by damanbaird** [comment]
ok, then it is in fact taking longer to reach the temp in my gcode, because it throws the pop up error and cancels before it even reaches temp. I was thinking the low temp feature was different than it is thought i could set it higher like in Marlin, but Marlin gave me issues.

**Comment by damanbaird** [comment]
Im aware that im asking the same thing as the closed issues #6 , i was thinking it was the same as  Marlins thermal protection

**Comment by precision** [comment]
duplicate #6
